apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    tag: {{ .Chart.Version }}
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}
    tag: {{ .Chart.Version }}
  type: {{ .Values.service.type }}
