namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111 # DRY: must be same as containerPort
  protocol: TCP
  type: ClusterIP
  
image:
  repository: michaeldtit/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbePath: /healthz
livenessProbePort: 3111 # DRY: must be same as containerPort

readinessProbePath: /healthz
readinessProbePort: 3111 # DRY: must be same as containerPort
